describe('Add Contact Tests', () => {  // arrow function is shorthand to get one function to call another
  it('Can add a new contact', () => {
    cy.visit('https://thinking-tester-contact-list.herokuapp.com')
    cy.get('#email').type('Gingerz346@gmail.com')
    cy.get('#password').type('YRbr3RJy@5YrNw')
    cy.get('#submit').click()
    cy.get('#add-contact').click()
    cy.get('#firstName').type('Test')
    cy.get('#lastName').type('User')
    cy.get('#birthdate').type('1995-01-02')
    cy.get('#email').type('Test.User@bar.com')
    cy.get('#phone').type('3333332222')
    cy.get('#street1').type('334 Maple Dr.')
    cy.get('#street2').type('Apt 5')
    cy.get('#city').type('Rockaway')
    cy.get('#stateProvince').type('NC')
    cy.get('#postalCode').type('44566')
    cy.get('#country').type('USA')
    cy.get('#submit').click()
    cy.get('#logout').click()
  })
})