describe('Add Contact Test then delete it', () => {  // arrow function is shorthand to get one function to call another
it('Delete a new contact', () => {
  // Create a random number
  let random = Math.floor(Math.random() * 1000)
    cy.visit('https://thinking-tester-contact-list.herokuapp.com')
    cy.get('#email').type('Gingerz346@gmail.com')
    cy.get('#password').type('YRbr3RJy@5YrNw')
    cy.get('#submit').click()
    cy.get('#add-contact').click()
    cy.get('#firstName').type('Test' + random)
    cy.get('#lastName').type('User2')
    cy.get('#birthdate').type('1995-05-02')
    cy.get('#email').type('Test2.User2@bar.com')
    cy.get('#phone').type('3333332222')
    cy.get('#street1').type('334 Palm Dr.')
    cy.get('#street2').type('Apt 5')
    cy.get('#city').type('Rockaway')
    cy.get('#stateProvince').type('CA')
    cy.get('#postalCode').type('44566')
    cy.get('#country').type('USA')
    cy.get('#submit').click()
    // Go to contacts details page:
    cy.contains('Test' + random + ' User2').click()
    cy.get('#delete').click()
    cy.on('window:confirm', () => true)
    cy.get('.contactTableBodyRow').contains('Test' + random + 'User2').should('not.exist')
//    cy.get('#logout').click()
  })
})