describe('Update Contact Tests', () => {  // arrow function is shorthand to get one function to call another

    beforeEach(() => {
        cy.login()
    })
  it('Can update a contact', () => {
  // Create a random number
  let random = Math.floor(Math.random() * 1000)
    cy.addContact(random)
    cy.contains('Test' + random + ' User2').click()
    cy.get('#edit-contact').click()
    cy.get('#firstName').clear()
    cy.get('#firstName').clear().type('Update' + random)
    cy.get('#lastName').clear().type('Person')
    cy.get('#birthdate').clear().type('2001-02-03')
    cy.get('#email').clear().type('foo@bar.com')
    cy.get('#phone').clear().type('3333220022')
    cy.get('#street1').clear().type('334 Bamboo Dr.')
    cy.get('#street2').clear().type('Apt 15')
    cy.get('#city').clear().type('Faraway')
    cy.get('#stateProvince').clear().type('CO')
    cy.get('#postalCode').clear().type('99566')
    cy.get('#country').clear().type('USA')
    cy.get('#submit').click()
    cy.get('#return').click()

    cy.contains('Update' + random + ' Person').click()
    cy.get('#firstName').should('contain', `Update${random}`)
    cy.get('#lastName').should('contain', 'Person')
    cy.get('#birthdate').should('contain', '2001-02-03')
    cy.get('#email').should('contain', 'foo@bar.com')
    cy.get('#phone').should('contain', '3333220022')
    cy.get('#street1').should('contain', '334 Bamboo Dr.')
    cy.get('#street2').should('contain', 'Apt 15')
    cy.get('#city').should('contain', 'Faraway')
    cy.get('#stateProvince').should('contain', 'CO')
    cy.get('#postalCode').should('contain', '99566')
    cy.get('#country').should('contain', 'USA')
//    cy.deleteContact()
//    cy.get('.contactTableBodyRow').contains('Update' + random + ' Person').should('not.exist')
//    cy.get('#logout').click()
  })

  it('Returns error when birthdate validation fails.', () => {
    let random = Math.floor(Math.random() * 1000)
    cy.addContact(random)
    cy.contains('Test' + random + ' User2').click()
    cy.get('#edit-contact').click()
    cy.get('#firstName').clear()
    cy.get('#birthdate').clear().type('09-11-2003')
    cy.get('#submit').click()
    cy.get('#error').should('contain', 'Validation failed: birthdate')
    cy.get('#cancel').click()
//    cy.deleteContact(random)
//    cy.get('.contactTableBodyRow').contains('Update' + random + ' Person').should('not.exist')
//    cy.get('#logout').click()
  })

  afterEach(() => {
    cy.deleteContact()
  })
})